# OpenAI secrets
OPENAI_API_KEY = "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"

# Astra DB secrets
ASTRA_ENDPOINT = "https://2fadfc83-462b-46d0-9528-34406411ffa7-us-east1.apps.astra.datastax.com"
ASTRA_TOKEN = "AstraCS:SznikZvoOjQkxGmoHxcAISvG:c1020e74139e52e510fb9c7f33bb81f261676df7eb6100899643341add9736b4"

# Optionally: LangSmith secrets for tracing
LANGCHAIN_TRACING_V2 = "false"
LANGCHAIN_ENDPOINT = ""
LANGCHAIN_API_KEY = ""
LANGCHAIN_PROJECT = ""

[passwords]
# Follow the rule: username = "password"
# Where username defines the Astra Vector Table and the rails.csv experience
forgext = "astradb"
datastax = "astradb"

[languages]
# Follow the rule: username = "localization_code"
# Where localization_code defines the language from localization.csv
forgext = "fr_FR"
datastax = "en_US"

[delete_option]
# Follow the rule: username = "delete_option"
# Where delete_option = True allows the 'Delete Context' button to be shown for that username
datastax = "True"
